name: Internalização de imagem - CrowdStrike Sensor
description: Utilize essa Issue para internalizar imagens do Sensor Falcon CrowdStrike
title: "[Bug]: "
labels: ["build", "issue"]
assignees:
  - Security
body:
  - type: markdown
    attributes:
      value: |
        Após executada, a imagem estará disponível no Jfrog Artifactory
  - type: dropdown
    id: type
    attributes:
      label: Selecione o tipo do sensor
      multiple: false
      options:
        - falcon-sensor
        - falcon-kac
        - falcon-container
        - shra
        - iar
    validations:
      required: true
   - type: dropdown
    id: architecture
    attributes:
      label: Selecione a arquitetura
      multiple: false
      options:
        - x86_64
        - Arm64
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Informe a versão do sensor
      description: Informe a versão do sensor desejada. Para maiores detalhes, consulte a documentação https://crowdstrike.com
      placeholder: ex. 7.x.xx.crowdstrike.us-2
    validations:
      required: true
