name: Internalização de imagem - CrowdStrike Sensor
description: Utilize essa Issue para internalizar imagens do Sensor Falcon CrowdStrike
title: "[Bug]: "
labels: ["build", "issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: browsers
    attributes:
      label: Selecione o tipo do sensor
      multiple: false
      options:
        - falcon-sensor
        - falcon-kac
        - falcon-container
        - shra
        - iar
    validations:
      required: true
  - type: input
    id: version2
    attributes:
      label: Versão do sensor
      description: Informe a versão do sensor desejada. Para maiores detalhes, consulte a documentação https://crowdstrike.com
      placeholder: ex. 7.x.xx.crowdstrike.us-2
    validations:
      required: false
