name: Internalização de imagem - CrowdStrike Sensor
description: Utilize essa Issue para internalizar imagens do Sensor Falcon CrowdStrike
title: "[Bug]: "
labels: ["build", "issue"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: browsers
    attributes:
      label: Selecione o tipo do sensor
      multiple: false
      options:
        - falcon-sensor
        - falcon-kac
        - falcon-container
        - shra
    validations:
      required: true
  - type: input
    id: version2
    attributes:
      label: Versão do sensor
      description: Informa a versão do sensor desejada
      placeholder: ex. 7.x.xx.crowdstrike.us-2
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

